### ISSUE TITLE
Unusable on Ubuntu / Gnome

### ISSUE THREAD

**Issue by S33G** [linonetwo/hyper-cli2gui#3]
Facing a problem when opening new tabs, or performing most operations (typing etc.)
On Ubuntu 19.04 / Gnome
Hyper 2.1.2

```Uncaught Exception:
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /home/charj/.hyper_plugins/node_modules/hyper-visual/dist/index.js:34:34792
    at /home/charj/.hyper_plugins/node_modules/hyper-visual/dist/index.js:34:38961
    at /home/charj/.hyper_plugins/node_modules/hyper-visual/dist/index.js:34:39902
    at u.(anonymous function) (/home/charj/.hyper_plugins/node_modules/hyper-visual/dist/index.js:34:39472)
    at /home/charj/.hyper_plugins/node_modules/hyper-visual/dist/index.js:34:39876
    at g (/home/charj/.hyper_plugins/node_modules/hyper-visual/dist/index.js:34:39914)
    at ReadFileContext.<anonymous> (/home/charj/.hyper_plugins/node_modules/hyper-visual/dist/index.js:34:37209)
    at ReadFileContext.callback (/home/charj/.hyper_plugins/node_modules/hyper-visual/dist/index.js:34:41021)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```

**Comment by linonetwo** [comment]
Is your history located at `~/.bash_history`?

If not, please tell me, I may need to add that.

**Comment by S33G** [comment]
It is indeed! @linonetwo

**Comment by linonetwo** [comment]
I got to know, it's caused by:

```js
    readJSON(`${cwd}/package.json`, console.error, false, (error, data) => {
      if (error) {
        return reject(error);
      }
      console.log(data);
      return resolve(Object.keys(data?.scripts));
    });
```

Where `data?.scripts` is null in

```js
Object.keys(data?.scripts)
```

I've publish a new version fixing this.

**Comment by S33G** [comment]
Have tested this and works great! Thanks for your hard work on this, it's a great plugin. @linonetwo
